steps:
# Step: Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - myfunction_cicd
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python312
  - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
  





